### ISSUE TITLE
missing top space

### ISSUE THREAD

**Issue by ghost** [JD342/arc-thunderbird-integration#1]
compared to the original firefox theme, its missing a slight space at the top of the tabs. You can see that when having the dark theme installed

![missingspace](https://cloud.githubusercontent.com/assets/5446005/23599067/fbee12ca-023e-11e7-8194-9e5927b6247a.png)

**Comment by nicolafio** [comment]
Version 0.2.0 should fix this issue. Let me know if it works as you intended.

**Comment by ghost** [comment]
that fixxed the issue!
thx for your work btw :+1:
