### ISSUE TITLE
Message Toolbar location

### ISSUE THREAD

**Issue by a-gerhard** [JD342/arc-thunderbird-integration#11]
The toolbar with reply, forward, and delete buttons gets pulled to the bottom when Styling is applied. There should be an option to still apply styling, but keeping the buttons above the message (i.e., in the middle of the window).
Also, when selecting multiple message, no styling is applied, i.e., the archive and delete buttons are thunderbird's default.

**Comment by pprw** [comment]
+1

**Comment by nicolafio** [comment]
Closing because same idea is repeated in #10. Check that issue for further updates.
