### ISSUE TITLE
Clean the SVG icons

### ISSUE THREAD

**Issue by heyhippari** [JD342/arc-thunderbird-integration#3]
You should save the icons as Optimized SVG so that they are a bit lighter and don't contain unnecessary Inkscape metadata.

**Comment by nicolafio** [comment]
I agree with you. They are kind of messy right now. I just took them from the original repos, tinted them in black and slapped them into the integration without worrying too much. A [recent commit](https://github.com/JD342/arc-thunderbird-integration/commit/96cf5e016e4d79a18262cf444f91f7d037d51122) in the development branch should make them more clean. The fix will be published in the next version.

**Comment by nicolafio** [comment]
Version 0.4.0 fixes this issue.
