### ISSUE TITLE
Message Body gone

### ISSUE THREAD

**Issue by MichiMolle** [JD342/arc-thunderbird-integration#4]
Hey thanks for your great work! I just installed 0.4., was using 0.2. until then, but now, the actual message body pane is gone / doesn't display anything. I did not experience this issue with the older version.

I'm running thunderbird 52.1.1 on an arch-linux machine

**Comment by jplatte** [comment]
Was just about to open another issue, then saw this and checked if I have this issue too.. Turns out I do :S

Also an archer, same version of Thunderbird.

**Comment by nicolafio** [comment]
Oops. Found the bug. Sorry! Will fix it when I'll have some free time as soon as possible.

In the meantime you can circumvent the bug by disabling styling in the mails view.

You can disable the specific styling by going to **Menu -> Preferences -> Display -> Arc Integration -> General Look (set it to Custom) -> Body (set it to Custom) -> Mails (set it to None)**.

**Comment by MichiMolle** [comment]
Thanks for your fast reply! The described workaround works like charm ;)

**Comment by jplatte** [comment]
Hm, the workaround doesn't work properly for me. When I set the General Look to Custom, even if every sub-setting is on dark, the tab bar is light and I can't read the tab titles anymore (except the one of the active tab). So I'll just disable this addon until there is a fix. But thanks anyway!

**Comment by nicolafio** [comment]
Can you take a screenshot?

**Comment by nicolafio** [comment]
@jplatte The tab bar styling depends on the "Frame" preference (General Look -> Frame). Is it set to "Dark"?

**Comment by jplatte** [comment]
General Look: Dark
![general_dark](https://user-images.githubusercontent.com/951129/27046874-5699c656-4fa6-11e7-904f-36e5e64d806b.png)

General Look: Custom, Frame: Dark, Body: Dark
![custom_dark_dark](https://user-images.githubusercontent.com/951129/27046880-591d693c-4fa6-11e7-87ee-a28072668713.png)

**Comment by nicolafio** [comment]
Very strange. I'll need to have a look at this in the near future. But currently I just released a new version (0.4.1) that should address the message body visibility bug. Let me know if it fixes it.

**Comment by jplatte** [comment]
0.4.1 works 🎉 
You should probably add an xpi to the release page though ;)

**Comment by nicolafio** [comment]
Oops. Forgot it. Will do it.

**Comment by nicolafio** [comment]
Done. I'm closing this issue. Feel free to open a new issue for the other problem if it is still occurring.

**Comment by jplatte** [comment]
Oh, I didn't think you had changed anything w.r.t. that. But after re-selecting the same options (after setting general to custom, I still had to change the other options to something other than dark and then back) that issue is now fixed as well! :)

**Comment by nicolafio** [comment]
I believe I have managed to find and fix the source of the problem you were describing. Version 0.4.3 should fix that problem.

**Comment by jplatte** [comment]
Nice! I now have it set to dark for everything and it does appear to work :)

**Comment by jplatte** [comment]
By the way, I'd love to help out with this project, mind setting up an IRC / matrix / gitter channel for communication?

**Comment by nicolafio** [comment]
@jplatte I created an IRC channel on [Freenode called #arc-thunderbird-integrarion](https://webchat.freenode.net/?channels=arc-thunderbird-integration).
