### ISSUE TITLE
Tab close-icon hover not displayed properly

### ISSUE THREAD

**Issue by MichiMolle** [JD342/arc-thunderbird-integration#6]
Thanks for the fast improvements regarding the last issue! I just noticed another minor problem. When hovering over the close-icon of any tab, the red close-icon does not replace the white one but is displayed below (see attached image). A fix would be great :) 
![bildschirmfoto von 2017-06-12 20-01-53](https://user-images.githubusercontent.com/9658246/27049978-453fbc98-4fb1-11e7-9b02-eda06cfd51f7.png)

**Comment by nicolafio** [comment]
I was not able to reproduce this visual bug on my version of Thunderbird (45.8.0). I successfully reproduced it in a more recent version (52.1.1).

Version 0.4.2 of the integration should address this bug. Let me know if it works.

**Comment by weber-s** [comment]
Hi. Thank you very much for this plugin.

I have Thunderbird 52.4.0 + version 0.4.3 and the bug is fixed. So I suppose it works 👍
