### ISSUE TITLE
Lightning Calendar current day highlight

### ISSUE THREAD

**Issue by statnmap** [JD342/arc-thunderbird-integration#8]
First of all, thank you for this plugin. The dark theme is really amazing.
I have a small visual request. 
In the lightning calendar (with multiweek or month view), the current day is only different from the other days by its date number being bold. Even if I may know which day we are today, I find it difficult to see it quickly on the calendar.
Could you find a way to make it a little more highlighted? For instance, with a thin blue border ?

Similarly, the day currently selected is only different with its date number being lighter (in dark theme). Could you also find a way to highlight it a little more ? Maybe with a different background (This is slightly the case for weekends but not for other week days) ? 

Thanks

**Comment by nicolafio** [comment]
The calendar styling is currently work in progress. But in the current version (0.4.x) the background coloring of the calendar cells is not altered. So the current day has a blue-ish background, while the selected day is yellow-ish, those are the standard colors in the Lightning extension. Are you using some other theming along with the integration?

_Multiweek view_
<img src="https://user-images.githubusercontent.com/11964463/27995708-29496c14-64d3-11e7-9c0e-85ff6da129b2.png" height="200"></img>
_Month view_
<img src="https://user-images.githubusercontent.com/11964463/27995709-2c187106-64d3-11e7-81ac-9bbf9bb7b954.png" height="200"></img>

The styling is not yet complete though. I was thinking about going for a simplistic look, close to the appearance of the [GNOME's Calendar app](https://wiki.gnome.org/Apps/Calendar) under Arc Theme. But I will take your suggestion into consideration, maybe I will put some blue-ish border coloring.

Thank you for your appreciation by the way!

**Comment by statnmap** [comment]
Indeed, I use the Arc-Dark GTK theme and the global dark gnome theme option is enabled.
So, this is the reason why...

**Comment by nicolafio** [comment]
I don't think that this is due to the system theme. The integration is meant to be used along with it. Those screenshots were taken with the GTK+ theme set on "Arc-Dark" and Global Dark Theme enabled.

Maybe this might be caused by other extensions/themes you have installed in Thunderbird? Or maybe you might be using versions of Thunderbird/Lightning that are different from the ones I use? I'm currently on Thunderbird 45.8.0 with Lightning 4.7.8.

**Comment by statnmap** [comment]
I am using Ubuntu 16.04, Thunderbird 52.2.1 and Lightning 5.4.
Here is what I see with GTK+ Theme "Arc-Dark" and classical Thunderbird theme:
![arcdark_thunderbirdclassic](https://user-images.githubusercontent.com/21193866/27996756-a254a626-64e9-11e7-91e1-f3fc20f49dc2.png)

And with your theme activated in Thunderbird:
![arcdarktheme-arcintegrationdark](https://user-images.githubusercontent.com/21193866/27996761-b511f836-64e9-11e7-9803-4d9726b599ae.png)

In both, the today date is selected.

**Comment by nicolafio** [comment]
This proves that more recent versions of the Lightning extension apply different styling based on the system theme variant. Thank you for letting me know. I will address this in the following version of the integration.

**Comment by statnmap** [comment]
You're welcome. Thank you.

**Comment by jplatte** [comment]
@JD342 I think it's not the version of Lightning that is causing this, but rather the setting "Optimize colors for accessibility" on the calendar tab. Try enabling that, and you should also have a darker calendar.

**Comment by statnmap** [comment]
Yes, after disabling "optimize colors for accessibility" in calendar settings, I have the same colors than @JD342.

**Comment by nicolafio** [comment]
I see. That check-box is toggling the `calendar.view.useSystemColors` preference. The current calendar styling does not seem to work very well when that option is enabled. The minimonth view shows up nicely, however.

In the following version I was thinking of applying custom coloring, therefore that option will no longer be of use. Thanks @jplatte for the clarification.
